version: "3.8"

services:
  memcached:
    image: memcached
    restart: always
    expose:
      - "11211"

  yopass:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: "--memcached=memcached:11211 --port 80"
    ports:
      - "127.0.0.1:80:80"
# yamllint disable rule:empty-values

# yamllint enable rule:empty-values
